version: "3.5"

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.2
    ports:
      - 37017:27017
    command: mongod --replSet my-mongo-set
    networks: 
      - mongo_replica_set
  mongo2:
    container_name: mongo2
    image: mongo:4.2
    ports:
      - 37018:27017
    command: mongod --replSet my-mongo-set
    networks: 
      - mongo_replica_set
  mongo3:
    container_name: mongo3
    image: mongo:4.2
    ports:
      - 37019:27017
    command: mongod --replSet my-mongo-set
    networks: 
      - mongo_replica_set

networks: 
  mongo_replica_set:
    name: mongo_replica_set
